name: generate-doc
run-name: Generate documentation

on: 
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/**"
      - "webview.nim"
      - "nimdoc.nim"

jobs:
  generate-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: stable
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate documentation
        run: nimble doc webview.nim

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        